// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as City$ReactTemplate from "./City.bs.js";
import * as Data$ReactTemplate from "./Data.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Cities"), $$Array.of_list(List.map((function (city) {
                        return React.createElement(City$ReactTemplate.make, {
                                    city: city,
                                    key: city[/* id */0]
                                  });
                      }), Data$ReactTemplate.cities)));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
